version: "3.4"
services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./secrets/tunnel.env
    networks:
      main:
        ipv4_address: 10.0.92.4
  client:
    container_name: viteClient
    build:
      context: ../client
      dockerfile: Dockerfile
    environment:
      - VITE_DEV_ORIGIN=https://demo.pauzemuzicale.com
      - VITE_GOOGLE_ID=217326008512-h0sev1ib4bh5es1i9ureevcjih8ktd7p.apps.googleusercontent.com
    volumes:
      - ./dist:/app/dist

  server:
    container_name: expressServer
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ORIGIN=https://demo.pauzemuzicale.com
      - NODE_ENV=production
      - MONGO_URL=mongodb://db:27017/pauzeMuzicale
      - JWT_REFRESH_SECRET=28901d2f-c0ba-4ebc-aa44-2a43ae4e9528
      - JWT_ACCESS_SECRET=f47cb99d-cb96-44a2-8577-05a47b0e6138
      - GOOGLE_ID=217326008512-h0sev1ib4bh5es1i9ureevcjih8ktd7p.apps.googleusercontent.com
      - GOOGLE_DOMAIN_CHECK=@gmail.com
      - FFMPEG_PATH=/usr/bin/ffmpeg

    restart: always
    ports:
      - 8080:8080
    volumes:
      - "C:\\Users\\ionut\\Desktop\\pauzeMuzicale\\music:/app/music"
      - "C:\\Users\\ionut\\Desktop\\pauzeMuzicale\\music1:/app/music1"
    depends_on:
      - db
      - client
    networks:
      main:
        ipv4_address: 10.0.92.3
  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - "C:\\Users\\ionut\\Desktop\\pauzeMuzicale\\db:/data/db"
    networks:
      main:
        ipv4_address: 10.0.92.2
networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "10.0.92.0/24"
