version: "3.4"
services:
  tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./secrets/tunnel.env
    networks:
      main:
        ipv4_address: 10.0.92.4
  client:
    container_name: viteClient
    build:
      context: ../client
      dockerfile: Dockerfile
    environment:
      - VITE_ORIGIN=https://cncmusic.ml
      - VITE_GOOGLE_ID=217326008512-h0sev1ib4bh5es1i9ureevcjih8ktd7p.apps.googleusercontent.com
      - VITE_SCHOOL_NAME=Colegiul National Alexandru Ioan Cuza
    volumes:
      - ./dist:/app/dist

  server:
    container_name: expressServer
    build: .
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - ORIGIN=https://cncmusic.ml
      - DB_URL=mongodb://db:27017/pauzeMuzicale
      - COOKIE_SECRET=28901d2f-c0ba-4ebc-aa44-2a43ae4e9528
      - JWT_SECRET=f47cb99d-cb96-44a2-8577-05a47b0e6138
      - GOOGLE_ID=217326008512-h0sev1ib4bh5es1i9ureevcjih8ktd7p.apps.googleusercontent.com
      - GOOGLE_DOMAIN_CHECK=@gmail.com
      - FFMPEG_PATH=/usr/bin/ffmpeg

    env_file:
      - ./secrets/express.env
    restart: always
    ports:
      - 8080:8080
    volumes:
      - "C:\\Users\\ionut\\projects\\Muzica_in_pauze\\ml\\data\\test_wav:/app/music"
    depends_on:
      - db
      - client
    networks:
      main:
        ipv4_address: 10.0.92.3
  db:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - "C:\\Users\\ionut\\Desktop\\pauzeMuzicale\\db:/data/db"
    networks:
      main:
        ipv4_address: 10.0.92.2
networks:
  main:
    ipam:
      driver: default
      config:
        - subnet: "10.0.92.0/24"

secrets:
  tunnel_token:
    file: ./secrets/secret_tunnel_token
